### ISSUE TITLE
SAME EMAIL, DIFFERENT ACCOUNT

### ISSUE THREAD

**Issue by Nick0925** [jeferbc/njoy#11]
USAR EL MISMO EMAIL PARA VARIAS SEDES DE RESTAURANTES O, UN MISMO CORREO PARA ABRIR VARIOS RESTAURANTES.

**Comment by jeferbc** [comment]
When we create a new restaurant, the user could use the same email for many restaurants, so, we need to change the restaurant login strategy, because we need that many restaurants has the same email, so how we know which restaurant are about to login if has the same email?. We need to create a unique name for restaurants and login with name and password

**Comment by jeferbc** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Change the company login strategy](https://trello.com/c/J13svIil/1-change-the-company-login-strategy)
